### ISSUE TITLE
TODO: Issues

### ISSUE THREAD

**Issue by Jeremy-Barnes** [Jeremy-Barnes/Critters#172]
High score (table, DTO, Page support - https://github.com/Jeremy-Barnes/Critters/issues/45)
Search Bar for games (JS side)
Game categories (config table, DTOs, JS filtering)

- [x] Make the password verify box work
- [x] Make the topbar a real thing with a dropdown menu
- [x] Make the user account update page look real and work on images
- [x] Game banner (dto)
- [x] Game screenshot 1 and 2 (DTO, table)

**Comment by Jeremy-Barnes** [comment]
Investigate this thing for games not in iframes:
https://stackoverflow.com/a/22567629/4885507
